# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
   apt:
     packages:
       - libgsl0-dev # for gls, which is an import of MBESS
